### ISSUE TITLE
请问快速开始运行了demo得到的结果是什么呢？

### ISSUE THREAD

**Issue by zjj100-zjj** [IAAR-Shanghai/UHGEval#28]

**Comment by Ki-Seki** [comment]
* 会得到一个名为SelectiveEvaluator_gpt-3.5-turbo.json的文件。
* 内容与这个文件类似，只不过条数少点：https://raw.githubusercontent.com/IAAR-Shanghai/UHGEval/main/archived_experiments/20231117/output/SelectiveEvaluator_gpt-3.5-turbo.json
* 生成的这个文件会放在这个文件夹下：https://github.com/IAAR-Shanghai/UHGEval/tree/main/output
