### ISSUE TITLE
请问这个能检测幻觉吗？还是幻觉评估？我能加入我的数据集让他判断每一个回答是否是幻觉呢？

### ISSUE THREAD

**Issue by zjj100-zjj** [IAAR-Shanghai/UHGEval#29]

**Comment by Ki-Seki** [comment]
* 这个不能检测幻觉，详情可以阅读论文：https://arxiv.org/abs/2311.15296
* 你可以加入自己的数据集，来实现特定的功能（例如您说的检测）。加入第三方数据集的功能可以参考 TruthfulQA 的做法，需要自己添加类似文件或目录：
  * 数据集文件：https://github.com/IAAR-Shanghai/UHGEval/tree/main/data/TruthfulQA
  * 数据集加载代码：https://github.com/IAAR-Shanghai/UHGEval/blob/main/uhgeval/dataset/truthfulqa.py
  * 数据集特定评测方式：https://github.com/IAAR-Shanghai/UHGEval/blob/main/uhgeval/evaluator/TruthQAEvaluator.py
  * 单元测试：https://github.com/IAAR-Shanghai/UHGEval/tree/main/tests
